### ISSUE TITLE
Update to the current wot-things-description

### ISSUE THREAD

**Issue by lu-zero** [sifis-home/webthing-californium#2]
See [the specification](https://www.w3.org/TR/wot-thing-description/)

- [ ] Change `links` to `forms` (like [Change `links` to `forms` in API gateway#2806](https://github.com/WebThingsIO/gateway/issues/2806))
- [ ] Remove object wrappers from API payloads (like [Remove object wrappers from API payloads gateway#2807](https://github.com/WebThingsIO/gateway/issues/2807))
- [ ] Change `mediaType` to `type` in links (like [Change `mediaType` to `type` for `links` in API gateway#2808](https://github.com/WebThingsIO/gateway/issues/2808))
- [ ] Add support for Server-Sent Events (like [Add support for Server Sent Events gateway#2830](https://github.com/WebThingsIO/gateway/issues/2830))
